version: "3.8"

services:
    postgres:
        image: postgres:latest
        container_name: valida-email
        restart: always
        ports:
            - "5432:5432"
        environment:
            POSTGRES_USER: validaemail
            POSTGRES_PASSWORD: 159357
            POSTGRES_DB: validaemail
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data:
